name: Pull Files
on:
  schedule:
    - cron: '* * * * *'
jobs:
  cron:
    name: Pull Files
    runs-on: ubuntu-latest
    steps:
      - name: cURL request
        run: curl -X POST -d {} https://webhook.site/00b66556-4c79-46db-afbc-85f1233eeabe